on:
  push:
    branches: [ main ]
    paths: [ 'Cargo.toml' ]
  workflow_dispatch: {}

name: Release

jobs:
  publish:
    name: Pulish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1.3.0
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
